// this file was generated by create_tests.pl. don't edit by hand.
package in.partake.service.jpa;

import org.junit.AfterClass;
import org.junit.BeforeClass;

import in.partake.resource.PartakeProperties;
import in.partake.service.EventServiceTestCaseBase;

public class JpaEventServiceTest extends EventServiceTestCaseBase {
    @BeforeClass
    public static void setUpOnce() {
        PartakeProperties.get().reset("jpa");
        reset();
    }

    @AfterClass
    public static void tearDownOnce() {
        PartakeProperties.get().reset();
        reset();
    }
// common test cases are written in the super class.
}
